In [1]:
import numpy as np

In [2]:
print(np.__version__,np.show_config)

1.15.1 <function show at 0x10f207048>


In [7]:
z= np.zeros(10)

In [10]:
print('%d bytes' %(z.size*z.itemsize))
#print('%d bytes' %np.zeros(10).size)  
#size是数组长度，itemsize是在内存中一个元素占多少字节

80 bytes


In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [12]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
z =np.arange(50)
z = z[::-1]
print(z)
#：1是 从0开始 取到1个数
#：-1 是从0开始取到-1个数 即最后一个
#::-1则是反转取数 间隔为1
#::1 是正向 取数间隔为 1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [29]:
z= np.arange(9).reshape((3,3))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
nz=np.nonzero([1,2,0,4,0])
print(nz)

(array([0, 1, 3]),)


In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.random((3,3,3))

array([[[0.18475301, 0.45084334, 0.68490286],
        [0.21554396, 0.23983019, 0.01708054],
        [0.73076959, 0.81091538, 0.00698997]],

       [[0.16227109, 0.28007107, 0.52516398],
        [0.14900288, 0.83756478, 0.0411292 ],
        [0.41709436, 0.39887763, 0.8318471 ]],

       [[0.45981169, 0.6675484 , 0.47600859],
        [0.20555636, 0.55220719, 0.93117373],
        [0.18075612, 0.49913373, 0.13064442]]])

In [35]:
z= np.random.random((10,10))

In [36]:
Zmi,Zma = z.min(),z.max()
print(Zmi,Zma)

0.057864899547049764 0.9812566919648353


In [37]:
z=np.random.random(30)
m=z.mean()
print(m)

0.46315458039106994


In [38]:
z=np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [49]:
print(0*np.nan)

nan


In [51]:
print(np.nan == np.nan)

False


In [46]:
np.inf >np.nan

False

In [47]:
np.nan - np.nan

nan

In [48]:
0*3 == 3*0.1

False

In [52]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [57]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2] =1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [58]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin)/(zmax-zmin)
print(z)

[[0.61165178 0.20308074 0.2868918  0.62282875 0.58894797]
 [1.         0.85592812 0.48645708 0.         0.3527478 ]
 [0.89762162 0.17904492 0.69728306 0.0233797  0.97927919]
 [0.57188668 0.59391353 0.7896287  0.30300557 0.21158905]
 [0.84791538 0.14670467 0.65555292 0.63024816 0.33189605]]


In [60]:
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [62]:
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [63]:
z=np.arange(11)
z[(3<z)&(z<=8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [64]:
print(sum(range(5),-1))

9


In [65]:
from numpy import *
print(sum(range(5),-1))

10


In [71]:
z=np.arange(5)

In [68]:
z**z

array([  1,   1,   4,  27, 256])

In [72]:
2<< z >>2

array([0, 1, 2, 4, 8])

In [73]:
z<-z

array([False, False, False, False, False])

In [75]:
z/1/1

array([0., 1., 2., 3., 4.])

In [76]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
print(np.array(0)/np.array(0))

nan


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [79]:
print(np.array(0)//np.array(0))

0


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [80]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


In [81]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ 3. -7. -7. -8. -9.  5. -6.  1.  7. -7.]


In [84]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1,z2))  #相同数

[9 1 3 8 0 1 0 9 4 0]
[5 6 4 6 2 8 6 6 5 8]
[4 8]


In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [86]:
yesterday =np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('昨天'+str(yesterday))
print('今天是'+str(today))
print('明天是'+str(tomorrow))

昨天2019-08-06
今天是2019-08-07
明天是2019-08-08


In [87]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [88]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [89]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [90]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [92]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [94]:
z=np.random.uniform(0,10,10)
print(z-z%1)

[7. 6. 2. 8. 7. 3. 1. 3. 1. 8.]


In [95]:
print(np.floor(z))

[7. 6. 2. 8. 7. 3. 1. 3. 1. 8.]


In [96]:
print(np.ceil(z)-1) #向上取整

[7. 6. 2. 8. 7. 3. 1. 3. 1. 8.]


In [98]:
print(z.astype(int))

[7 6 2 8 7 3 1 3 1 8]


In [100]:
print(np.trunc(z))

[7. 6. 2. 8. 7. 3. 1. 3. 1. 8.]


In [103]:
z=np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [104]:
def generate():
    for x in range(10):
        yield x
        
z=np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [108]:
np.linspace(0,1,11,endpoint=False)[1:]
# np.random.rand(11)#该方法域值为[0,1)

array([0.75318053, 0.64329219, 0.92254714, 0.89876494, 0.34927513,
       0.29303016, 0.91727944, 0.48472178, 0.00118829, 0.01538718,
       0.71282959])

In [110]:
z=np.random.random(10)
z.sort()
print(z)

[0.02995706 0.07396274 0.16619212 0.1961489  0.35780874 0.50069728
 0.71314447 0.73977207 0.74855543 0.8342568 ]


In [111]:
z=np.arange(10)
np.add.reduce(z)

45

In [112]:
a=random.randint(0,2,5)
b=random.randint(0,2,5)
equal=np.allclose(a,b)
print(equal)
#比较每个元素是不是相等

False


In [113]:
equal=np.array_equal(a,b)
print(equal)

False


In [114]:
z=np.zeros(10)
z.flags.writeable=False
z[0]=1

ValueError: assignment destination is read-only

In [115]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[1.11608531 0.97117992 0.85400211 0.811628   0.81784831 0.64999797
 0.68409158 0.40681749 0.71895414 0.91379702]
[1.0809823  0.80972559 1.02653523 0.60970179 0.60539654 0.15178299
 0.24615509 1.56086826 0.43375285 1.28518487]


In [119]:
z=np.random.random(10)
z[z.argmax()]=1

print(z)

[0.81875806 0.60957543 0.75985693 0.85681873 0.30745652 0.01391224
 0.57159825 1.         0.20747892 0.86308122]


In [122]:
z=np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),
                          np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [123]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.1636371179666


In [125]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [126]:
np.set_printoptions(threshold=np.nan)
z=np.zeros((16,16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [127]:
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

4
